### ISSUE TITLE
Bigtable: readRow() traces show up as cancelled

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable#108]

**Comment by rahulKQL** [comment]
This issue not reproducible. As of today only see the sent bytes in ReadRow after multiple attempts.
<img width="974" alt="ReadRow_traces_Jan_8th_2020" src="https://user-images.githubusercontent.com/42969463/72004114-bef9f680-3270-11ea-8566-d47fd9f2e15d.png">
