### ISSUE TITLE
Dependency Manage org.threeten:threetenbp

### ISSUE THREAD

**Issue by justinuang** [googleapis/java-bigtable#109]
In google-cloud-bigtable, https://github.com/googleapis/google-cloud-java/pull/6484, we declare a dependency on threetenbp, which had to be the same version as gax because of our dependency convergence enforcement.

**Comment by igorbernstein2** [comment]
google-cloud-clients doesn't exist anymore and we now manage our deps in google-cloud-bigtable-bom. We also have enabled renovate bot to make sure that we are using the latest version and have also added maven-enforcer to ensure that our deps aren't using a newer version. So closing this as obsolete
