### ISSUE TITLE
Allow to disable tracing

### ISSUE THREAD

**Issue by j-martin** [googleapis/java-bigtable#1140]
**Is your feature request related to a problem? Please describe.**
We use OpenCensus Tracing (to GCP Trace) throughout our system. Because of this, we get tons of spans created by the Bigtable client. Something like 75% of all our spans is generated by this library. There is no way (that I am aware) to filter out those spans.

**Describe the solution you'd like**
We would like to be able to disable tracking altogether. In the case below, the noop tracer could be used.

https://github.com/googleapis/java-bigtable/blob/0d197a5ab9b7ccd20091c1c6c4a794586d6a51dc/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java#L197-L222

Where we would configure via the [EnhancedBigtableStubSettings](https://github.com/googleapis/java-bigtable/blob/215148a58fb62188b25372c1b80df9cc50bc0809/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java).

**Describe alternatives you've considered**
- Ignoring traces, but that's not an option.
- Reducing the sampling would still end up with the same ratio (75%) of span being from this library. 

**Additional context**
Any other context or screenshots about the feature request.

**Comment by davidnadeau** [comment]
I am also using opencensus tracing and experiencing a large percentage of my spans coming from the bigtable client. This has required us to sample our traces significantly. 

Are there any ways to stop emitting these traces? I've tried setting the traceProvider to the noop tracer factory (BaseApiTracerFactory). But it doesn't seem to be respected by the bigtable client:
```scala
    settingsBuilder
      .stubSettings()
      .setTracerFactory(BaseApiTracerFactory.getInstance())
```

**Comment by mutianf** [comment]
You can create a custom sampler that filters out Bigtable spans:

```
    public static class MySampler extends Sampler {

        private final Sampler childSampler;

        MySampler(Sampler child) {
            this.childSampler = child;
        }

        @Override
        public boolean shouldSample(@Nullable SpanContext parentContext, @Nullable Boolean hasRemoteParent, TraceId traceId, SpanId spanId, String name, List<Span> parentLinks) {
            if (name.contains("Bigtable")) {
                return false;
            }
            return childSampler.shouldSample(parentContext, hasRemoteParent, traceId, spanId, name, parentLinks);
        }

        @Override
        public String getDescription() {
            return "from my sampler";
        }
    }
```

And setting up your Tracing config with:

```
        Tracing.getTraceConfig().updateActiveTraceParams(
                Tracing.getTraceConfig().getActiveTraceParams().toBuilder()
                        .setSampler(new MySampler(Samplers.probabilitySampler(0.1)))
                        .build()
        );
```
