### ISSUE TITLE
Question - what is the difference between bigtable-client-core and google-cloud-bigtable?

### ISSUE THREAD

**Issue by sanjuthomas** [googleapis/java-bigtable#127]
I'm confused - I have seen two clients in the maven, so far I used the bigtable-client-core and it worked fine. Recently I noticed google-cloud-bigtable. I was wondering which one google recommend for CRUD operations on Bigtable? 

https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-client-core/1.12.1
https://mvnrepository.com/artifact/com.google.cloud/google-cloud-bigtable/1.8.0

**Comment by rahulKQL** [comment]
`bigtable-client-core` is a core module to wrap the HBase interface over Bigtable operations. It is scheduled to be deprecated soon.

Going forward I would recommend you to use `google-cloud-bigtable`. It provides a user-friendly interface for settings as well as data & admin client. Besides CURD operation it also exposes other advance options(Callables, Batcher, etc.) to integrate with your applications.

**Comment by sanjuthomas** [comment]
Thanks, @rahulKQL
