### ISSUE TITLE
Update renovate.json with dependencies to exclude and group.

### ISSUE THREAD

**Issue by kolea2** [googleapis/java-bigtable#13]

**Comment by chingor13** [comment]
gRPC and protobuf were in there pre-bom. We can likely remove these from the templates as we should be importing dependency versions for these from a grpc-bom or protobuf-bom and it will only need a single version bump. OpenCensus has yet to publish a bom, so we still want the grouping.

**Comment by igorbernstein2** [comment]
I just wanted to clarify my comment from https://github.com/googleapis/java-bigtable/pull/11/files#r337175152.

> Should we include:
> * gax & gax-grpc?
> * google-cloud-core & google-cloud-core-grpc?
> * auto-value & auto-value-annotations
> 

I didn't mean that we should exclude those deps, but that they should be grouped together. ie gax & gax-grpc should be treated as the same group and google-cloud-core & google-cloud-core-grpc should be treated as another group. I didn't mean that they should be excluded

**Comment by kolea2** [comment]
Thanks @igorbernstein2, I've updated the title to be more clear. I was thinking we should take a look at the `ignoredDeps` from google-cloud-java and add as needed.

**Comment by kolea2** [comment]
This should be fixed in #123
