### ISSUE TITLE
readRowAsync cancelled results in server side metrics

### ISSUE THREAD

**Issue by mattfsmith** [googleapis/java-bigtable#1522]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-bigtable/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4. bigtable version(s):

#### Steps to reproduce

  1. review code example below
  2. Review cancelled messages

![image](https://user-images.githubusercontent.com/15573742/202815060-eec31adf-aa4d-4758-b666-f66a32caa374.png)

#### Code example

```
//java example
ApiFuture<Row> futureResult = bigtableDataClient.readRowAsync(tableId, ByteString.copyFromUtf8(rowKey));
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by igorbernstein2** [comment]
It seems like this was already fixed in https://github.com/googleapis/java-bigtable/pull/1326.

What version are you using? Can you copy/paste the output of `mvn dependency:tree`?

**Comment by igorbernstein2** [comment]
Confirmed, this was already fixed. The bug report was for version 2.8.0
