### ISSUE TITLE
BigTable: conditional increments does not support filtering/optimistic locking

### ISSUE THREAD

**Issue by krishna81m** [googleapis/java-bigtable#1650]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: any, latest
3. Java version: 1.8
4. bigtable version(s): any, latest

#### Steps to reproduce
When inserting or updating columns, concurrent updates to Increment is causing data loss without optimistic locking like capabilities that we already provide but not enabled for Increment APIs. What is the work around to this problem?

  1. Conditional Updates works to filter before writing/updating any column: https://github.com/googleapis/java-bigtable/blob/main/samples/snippets/src/main/java/com/example/bigtable/WriteConditionally.java
  3. Increment column does not have the same filter capability to conditionally increment: https://github.com/googleapis/java-bigtable/blob/main/samples/snippets/src/main/java/com/example/bigtable/WriteIncrement.java

#### Code example

```java
String rowkey = "phone#4c410523#20190501";
      Mutation mutation =
          Mutation.create().setCell(COLUMN_FAMILY_NAME, "os_name", timestamp, "android");
      Filter filter =
          FILTERS
              .chain()
              .filter(FILTERS.family().exactMatch(COLUMN_FAMILY_NAME))
              .filter(FILTERS.qualifier().exactMatch("os_build"))
              .filter(FILTERS.value().regex("PQ2A\\..*"));
      ConditionalRowMutation conditionalRowMutation =
          ConditionalRowMutation.create(tableId, rowkey).condition(filter).then(mutation);
      boolean success = dataClient.checkAndMutateRow(conditionalRowMutation);

// No Optimistic Lock capability for increment??
ReadModifyWriteRow mutation =
          ReadModifyWriteRow.create(tableId, rowkey)
              .increment(COLUMN_FAMILY_NAME, "connected_cell", -1);
      Row success = dataClient.readModifyWriteRow(mutation);

```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below

**Comment by igorbernstein2** [comment]
Our api doesnt currently support this usecase. For low contention you can workaround this limitation by doing a read + conditional write loop:

1. Read the row the intended row with including the value to increment
2. send a conditional mutation with a condition that includes the value from 1 and the mutation for the incremented value
3. check if it applied, if not repeat
