### ISSUE TITLE
RowCells are not actually serializeable

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable#384]
RowCells might contain UnmodifiableLazyStringList for values, which are not actually serializable. 
We need to add custom hooks to RowCell to fix serialization.

The primary issue is that labels are a UnmodifiableLazyStringList, which is not serializeable

**Comment by dmitry-fa** [comment]
@igorbernstein2, the bad news: `RowCell` is abstract and marked as `@AutoValue`, which means its implementation is generated.
If I read [the @AutoValue documentation](https://chromium.googlesource.com/external/github.com/google/auto/+/auto-value-1.0/value/#serialization) correctly we can't customize serialization. I see several ways of fixing the issue, but none of them looks good to me:

- RowCell instances are created by `RowCell.create()` method, implemented like:
```
public static RowCell create(... List<String> labels, ...) {
   return new AutoValue_RowCell(...,labels);
}
```
 method. We can do something like:
```
  try {
     tryToSerialize(labels)
  } catch (Exception e) {
     labels = ArrayList.of(labels)
  }
```  
or simple:
```
  labels = ArrayList.of(labels)
```

- We can add post-compilation step to the build to instrument AutoValue_RowCell.class  and insert `private void writeObject()` method. (a bit of hardcore)

- Stop using `@AutoValue` and implement the custom serialization in the manually implemented subclass.


Do you have any preferences or suggestions?

**Comment by igorbernstein2** [comment]
I think the easiest way would be to update create

```java
public static RowCell create(
      @Nonnull String family,
      @Nonnull ByteString qualifier,
      long timestamp,
      @Nonnull List<String> labels,
      @Nonnull ByteString value) {
    // Ensure that the list is serializable and optimize for the common case
    labels = labels.isEmpty() ? ImmutableList.of() : ImmutableList.copyOf(labels);
    return new AutoValue_RowCell(family, qualifier, timestamp, value,ImmutableList. labels);
  }
```
