### ISSUE TITLE
Add a BOM artifact

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-bigtable#48]
Please publish a google-cloud-bigtable-bom pom artifact that contains the synced versions of artifacts from this repository. We will consume them upstream in the google-cloud-bom as a single version rather than trying to keep 7+ artifact versions synced.

**Comment by chingor13** [comment]
Here's an example from the translate repo: https://github.com/googleapis/java-translate/blob/master/google-cloud-translate-bom/pom.xml

Note that the version of the pom is the same as the primary artifact

**Comment by kolea2** [comment]
👍 already working on it!
