### ISSUE TITLE
Adding the option for users to use Java System Properties to set Emulator configurations. 

### ISSUE THREAD

**Issue by fosky94** [googleapis/java-bigtable#552]
What you want to happen?
Add the option for users to use Java System Properties to set Emulator configurations in `Builder newBuilder()`. Some users may want to set this configuration at Java Platform level (Java properties) instead of at OS level (env variables).

A proposed change could be to add the following lines in the `public static Builder newBuilder()` function right after `String hostAndPort = System.getenv(BIGTABLE_EMULATOR_HOST_ENV_VAR);`:

`if (Strings.isNullOrEmpty(hostAndPort)) {
      hostAndPort = System.getProperty(BIGTABLE_EMULATOR_HOST_SYS_VAR)
}`

Files to be changed are [1] and [2]

[1] https://github.com/googleapis/java-bigtable/blob/master/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
[2] https://github.com/googleapis/java-bigtable/blob/master/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java

**Comment by igorbernstein2** [comment]
hi,
Thanks for the suggestion. However I would like to limit the number of ways to do the same thing. The core approach is to use the java api to connect to the emulator. The environment variable was added to allow cross language compatibility (ie all of the bigtable clients respect that variable).
If further integrations are needed like system properties, managed beans, etc they can be implemented in the application using a simple factory
