### ISSUE TITLE
BulkMutation result statistics

### ISSUE THREAD

**Issue by helanyao** [googleapis/java-bigtable#584]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
We want to import data to bigtable with bigtable api. We would like to know the statistics of the import such as how many has been imported successfully and how many has been failed. Also, we want to save those failed items and try to reimport them again.

ApiFuture<Void> apiFuture = dataClient.bulkMutateRowsAsync(bulkMutation);
In this result, there is no result returned.

How can we achieve the goal? Your help is much appreciated.

**Comment by helanyao** [comment]
Can someone help here?

**Comment by kolea2** [comment]
Hi @helanyao, does this javadoc help with what you are trying to achieve (specifically printing errors with `onFailure`)? https://github.com/googleapis/java-bigtable/blob/master/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java#L1183-L1197

**Comment by igorbernstein2** [comment]
hi,
bulkMutateRowsAsync will throw an exception if any entry fails. The exception `BulkMutationFailure` will contain data about which entries failed
