### ISSUE TITLE
Bigtable emulator does not support ARM

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-bigtable#677]
It looks the the emulator only works on x64 architectures for Linux, OSX, and Windows.

**Comment by suztomo** [comment]
Memo for the error

```
~/suztomo/java-bigtable/google-cloud-bigtable-emulator$ mvn test -DtrimStackTrace=false  -Dtest=com.google.cloud.bigtable.emulator.v2.EmulatorTest 

...
INFO] Running com.google.cloud.bigtable.emulator.v2.EmulatorTest
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in com.google.cloud.bigtable.emulator.v2.EmulatorTest
[ERROR] com.google.cloud.bigtable.emulator.v2.EmulatorTest.testDataClient  Time elapsed: 0.016 s  <<< ERROR!
java.lang.UnsupportedOperationException: Unsupported architecture: aarch64
	at com.google.cloud.bigtable.emulator.v2.Emulator.getBundledResourcePath(Emulator.java:236)
	at com.google.cloud.bigtable.emulator.v2.Emulator.createBundled(Emulator.java:65)
	at com.google.cloud.bigtable.emulator.v2.EmulatorTest.setUp(EmulatorTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```


From Emulator.java:
```
    String unformattedArch = System.getProperty("os.arch");
    String arch;

    switch (unformattedArch) {
      case "x86":
        arch = "x86";
        break;
      case "x86_64":
      case "amd64":
        arch = "x86_64";
        break;
      default:
        throw new UnsupportedOperationException("Unsupported architecture: " + unformattedArch);
    }

    return String.format(
        "/gcloud/bigtable-%s-%s/platform/bigtable-emulator/cbtemulator%s", os, arch, suffix);

```

**Comment by igorbernstein2** [comment]
We need to start publishing aarch64 to gcloud sdk and then we can update this wrapper

**Comment by tkaymak** [comment]
Is the publishing on the horizon? <3

**Comment by liufuyang** [comment]
Any update and temproray solutions for this? 

This is what I see if I try to run `gcloud beta emulators bigtable start`
```
WARNING: The ARM versions of the components [bigtable] are not available yet. To download and execute the x86_64 version of the components, please install Rosetta 2 first by running the command: softwareupdate --install-rosetta.
ERROR: (gcloud.beta.emulators.bigtable.start) The following components are unknown [bigtable].
```

**Comment by alejandrolujan** [comment]
Any updates on this? Is there a plan to release an ARM-compatible emulator? Any timelines?

Shopify is moving all of its engineers to Apple M1 laptops and this is blocking several repositories from being compatible with the ARM architecture.

**Comment by rameshdharan** [comment]
Hi @liufuyang and @alejandrolujan, we can confirm that the emulator update for ARM64 (macOS and Linux) is complete, and should be included in a gcloud SDK release happening soon (currently I'd expect this to release in mid-December). 

You can follow the Cloud SDK release notes here, and the ARM emulator update will be noted there once included in the release: 
https://cloud.google.com/sdk/docs/release-notes

As a workaround I believe It's possible to manually build the emulator ([it's OSS](https://github.com/googleapis/google-cloud-go/tree/main/bigtable/cmd/emulator)) with a golang SDK and then put the binary in the right place but I have not tried it - though since the emulator is releasing shortly you may just want to wait for it rather than trying such workarounds?

**Comment by sap1ens** [comment]
Hey @rameshdharan, thanks for the update! I assume this library will be updated at the same time? We don't use the SDK, but this library directly.

**Comment by rameshdharan** [comment]
@sap1ens yes, thanks for mentioning that - I believe we will still need to (trivially) update this library shortly thereafter; specifically AIUI the google-cloud-bigtable-emulator's pom.xml will need to include `bigtable-darwin-arm` and `bigtable-linux-arm` in the `<componentNames>` [section](https://github.com/googleapis/java-bigtable/blob/main/google-cloud-bigtable-emulator/pom.xml#L54), and that will start working once the components are released (via the Cloud SDK release).

**Comment by meredithslota** [comment]
Confirming that it looks like ARM64 support was added in the emulator in late 2021: https://cloud.google.com/sdk/docs/release-notes#36700_2021-12-14 so this should be unblocked now.

**Comment by caseyduquettesc** [comment]
Seems like it was fixed? https://github.com/googleapis/java-bigtable/pull/1094
