### ISSUE TITLE
Add bulk read api

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable#7]
bigtable-client-core currently has a feature to use ReadRows for bulk reads. I think we can easily  port over this functionality using the Batcher api similar to how bulk mutations work:

* Add `Batcher<ByteString, Row> newBulkReadBatcher(tableId, filter)` to the client and stub surface
  * Have it return a instance BatcherImpl instance that wraps the ReadRowsCallable
* Add a BulkReadRowsRequestBuilder that wraps a Query and adds ByteString row keys
* Add a ReadRowsBatchingDescriptor that can map results back to entry futures
* Expose batching read settings as bulkReadRowsSettings on the stub

Things to consider:
* Need to be careful with tracing to avoid creating confusing spans
* Need to make sure to expose the ability to set a filter
* Need to be careful with UnaryCallableSettings to make sure that bulk & streaming settings dont conflict

**Comment by crwilcox** [comment]
@kolea2 how do you think we want to extend this to other clients?
