### ISSUE TITLE
Bigtable TimestampRangeFilter generates invalid bounds

### ISSUE THREAD

**Issue by mchalek** [googleapis/java-bigtable#98]
The bigtable client allows queries to specify that rows be filtered by their insert timestamp.  The filter supports bounded and unbounded ranges, with open or closed endpoints.

Unfortunately, the implementation of the query builder contains logic that causes the client to generate queries that Bigtable rejects.

[Here](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Filters.java#L532-L557) is where the client translates its user-specified timestamp range filters into more generic filter `RowFilter` that are ultimately translated into protobufs for submission to Bigtable.

You can see that, for open start bounds or closed end bounds, the client adds 1 microsecond to the bound, presumably in an attempt to deal with the fact that Bigtable's [TimestampRange](https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.TimestampRange) filter parameter does not support exclusive (open) lower bounds or inclusive (closed) upper bounds.

However, Bigtable also does not accept timestamp range filters with precision below 1 millisecond.  Presumably this is because the minimum granularity of Bigtable timestamps is 1 ms, as suggested [here](https://cloud.google.com/bigtable/docs/reference/admin/rpc/google.bigtable.admin.v2#google.bigtable.admin.v2.Table.TimestampGranularity) in the Bigtable documentation, although the restriction on the filter parameters does not appear to be definitively stated anywhere.

The consequence of this is that Bigtable rejects any queries generated by the client using open start bounds or closed end bounds.

I believe that a valid fix for this would be to add one _millisecond_ rather than one _microsecond_ to each of the places where these bounds are generated.  However, if Bigtable ever does add microsecond support, then this would become invalid.  Perhaps a more thorough solution would be to query the Bigtable Admin API on the creation of the client, to confirm that the timestamp granularity is set to milliseconds?

Or alternatively, perhaps the client should simply throw an exception to reject the specification of open start bounds or closed end bounds?

**Comment by rahulKQL** [comment]
Thanks for adding detailed issue, However, I need more clarity on below points:


> Unfortunately, the implementation of the query builder contains logic that causes the client to generate queries that Bigtable rejects.
 
 Do you have any valid filter criteria that are being rejected? Because the combination you mentioned were all seems valid for Bigtable and I think you should be able to get the results.


> However, Bigtable also does not accept timestamp range filters with precision below 1 millisecond.

 The `Query.filter()` accepts values in microseconds, you can give any range but the rows will have timestamp in 1000s only.


> The consequence of this is that Bigtable rejects any queries generated by the client using open start bounds or closed end bounds.

Do you mean [this](https://gist.github.com/rahulKQL/e8c062afd3d987f5f79a88192389a0f5#file-timestamprangeex-java-L85-L104) type of ranges?  If yes, Then it works completely fine with this bigtable client.

**Comment by mchalek** [comment]
hi @rahulKQL , 

thank you for the response.  The code that you linked uses the Bigtable emulator.  Perhaps the client works with the Bigtable emulator, but it does not work with Google Cloud Bigtable due to the restrictions described in the documentation that I linked in my initial post.

Here is a scala snippet that will reproduce the error by requesting a timestamp range with an open start bound:
```scala
import com.google.cloud.bigtable.data.v2.BigtableDataClient
import com.google.cloud.bigtable.data.v2.models.{Query, Filters}
import scala.collection.JavaConverters._

val dataClient = BigtableDataClient.create(<my-project>, <my-instance>)
val query = Query.create(<my-table-name>)
query.rowKey("any-key")
query.filter(Filters.FILTERS.timestamp.range.startOpen(1574349196000000L))

dataClient.readRows(query).iterator.asScala.toIndexedSeq

com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error in field 'timestamp_range_filter' : Timestamp granularity mismatch. Expected a multiple of 1000 (millisecond granularity), but got 1574349196000001.
...
```

**Comment by rahulKQL** [comment]
Yes, It fails for me too with actual bigtable with those ranges.

**Comment by mchalek** [comment]
Awesome, thanks for confirming!  I should have included a snippet in my original post.

**Comment by igorbernstein2** [comment]
Hi @mchalek,

Thanks for the reporting the bug. This is an unfortunate oversight on my part and as you pointed out adding a millisecond would break if Bigtable enabled microsecond resolution. And since this client doesn't have a concept of opening a table, there is no opportune time to fetch the table metadata to inspect the resolution.

It will take us a bit of time to discuss and address this bug internally. So this bug will be quiet for a little while, but please rest assured that this is something that we are working on

**Comment by mchalek** [comment]
Great, thanks for the update @igorbernstein2 !

**Comment by elonybear** [comment]
Hi, is there an update on the status of this issue?

**Comment by igorbernstein2** [comment]
Not yet

**Comment by adam-singer** [comment]
Was bit by this bug today, the quick work around for us was (scala)

```
  class ExactTimestampFilter(exactTimestampMillis: Long) extends Filter {
    override def toProto: RowFilter = {
      val builder = com.google.bigtable.v2.TimestampRange.newBuilder()
      builder.setStartTimestampMicros(exactTimestampMillis * 1000)
      builder.setEndTimestampMicros((exactTimestampMillis + 1) * 1000)
      RowFilter.newBuilder.setTimestampRangeFilter(builder.build).build
    }
  }
```

From a users point of view, the documentation around expectation of timestamps being clamped to millis with api backends only accepting/validating micros (while emulators YOLO) and APIs not clear on either is painful.

**Comment by WhyUnspoken** [comment]
Stumbled over the same issue, too. My workaround for this:
`FILTERS.timestamp().range().startClosed(timestamp * 1000).endOpen((timestamp + 1) * 1000)`
BTW: Google Docs now state that startOpen() and endClosed() is not supported by the java client anymore. 
They have the same issue.

**Comment by mutianf** [comment]
This issue should be fixed from the bigtable server side now.
