### ISSUE TITLE
Dependency version UpperBound checks fail on some versions 

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable#986]
`google-cloud-conformance-tests` has a few dependencies that conflict with our main dependency versions. To avoid conflicts, we have wildcard exclusions. Unfortunately that seems broken in some versions of maven (3.6.1).

For the time being, I expanded the excludes list to explicitly list the broken deps, but we will need a more maintainable solution

**Comment by kolea2** [comment]
@igorbernstein2 since we reverted this I'm going to close
